export default {
  // 文本颜色
  fontColor: '#000000',
  // 文本字体
  fontFamily:
    '"Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial',
  // 文本字号
  fontSize: 12,
  // 文本行高比
  lineHeight: 1.5,
  // 文本水平对齐方式
  textAlign: 'left',
  // 文本垂直对齐方式
  textBaseline: 'top',
  // 线段文字块填充色
  textRectFill: '#ffffff',
  // 线段文字块边框色
  textRectStroke: '#000000',
  // 线段文字块边框色[激活状态]
  textRectActiveStroke: '#E79D32',
  // 线段组织类型0[固定锚点]、1[手动拖动]
  lineMode: 1,
  // 线段连接类型
  lineJoin: 'miter',
  // 线段宽度
  lineWidth: 2,
  // 线段颜色
  lineStroke: '#000000',
  // 线段颜色[激活状态]
  lineActiveStroke: '#E79D32',
  // 线段箭头填充色
  arrowFill: '#000000',
  // 线段箭头边框色
  arrowStroke: '#000000',
  // 线段箭头填充色[激活状态]
  arrowActiveFill: '#E79D32',
  // 线段箭头边框色[激活状态]
  arrowActiveStroke: '#E79D32',
  // 默认线段类型
  defaultLineName: 'polyline',
  // 默认箭头起始点类型
  defaultFromArrowType: '',
  // 默认箭头终止点类型
  defaultToArrowType: 'triangleSolid',
  // 表节点默认名称
  tableName: '',
  // 表节点默认宽度
  tableDefaultW: 100,
  // 表节点默认高度
  tableDefaultH: 100,
  // 表节点操作模式0[收起展开]、1[切换组和表结构]
  tableHandle: 1,
  // 表节点填充色
  tableNodeFill: '#ffffff',
  // 表节点边框色
  tableNodeStroke: '#c1c7cd',
  // 表节点边框颜色
  tableNodeBorderColor: '#0C64EB',
  // 表节点填充距离
  tablePadding: 10,
  // 表节点表名背景色[非父节点]
  tableTitleFill: '#e1e7ed',
  // 表节点表名背景色[父节点]
  tableGroupTitleFill: '#d0e2ff',
  // 表节点主键背景色
  tablePrimarykeyFill: '#fffaf1',
  // 锚点曲率
  anchorRadius: 5,
  // 锚点填充色
  anchorFill: '#ffffff',
  // 锚点边框色
  anchorStroke: '#ff0000',
  // resizer边框色
  resizerStroke: '#0C64EB',
  // resizer填充色
  resizerFill: '#ffffff',
  // resizer默认大小
  resizerWidth: 10,
  // resizer cursor
  resizerCursors: ['nw-resize', 'ne-resize', 'se-resize', 'sw-resize'],
  // 是否显示缩略图
  thumbnail: false,
  // thumbnail默认宽度
  thumbnailW: 240,
  // thumbnail默认高度
  thumbnailH: 140,
  // thumbnail底色
  thumbnailFillBg: '#ffffff',
  // thumbnail 移动rect颜色
  thumbnailFillRect: 'rgba(0,0,0,0.2)',
}
